/* ============================================================================
   Master Agent -> Subagent -> data_to_chart : WORKING REPRODUCTION
   ----------------------------------------------------------------------------
   Counter-example to the reported issue:
     "unable to render interactive charts when using a Master Agent-Subagent
      architecture ... data_to_chart on the Master Agent when it consumes data
      generated by the sql_execution tool running within a Subagent."

   Verified on account SFPSCOGS-RRAMAN_AWS_SI (Snowflake 10.32.102),
   2026-09-14. The master agent DOES invoke data_to_chart on subagent-sourced
   data and DOES emit a response.chart event containing a full Vega-Lite v5
   chart spec.

   Run top to bottom as a role with CREATE AGENT on SNOWFLAKE_INTELLIGENCE.AGENTS.
   ============================================================================ */

/* ---------------------------------------------------------------------------
   STEP 1 - Sample data (no customer data needed)
   --------------------------------------------------------------------------- */
CREATE DATABASE IF NOT EXISTS CHART_SUBAGENT_DEMO;
CREATE SCHEMA   IF NOT EXISTS CHART_SUBAGENT_DEMO.DEMO;

CREATE OR REPLACE TABLE CHART_SUBAGENT_DEMO.DEMO.PRODUCTS (
  PRODUCT_ID   NUMBER(9,0)  NOT NULL COMMENT 'Surrogate key for the product',
  PRODUCT_NAME VARCHAR(100) NOT NULL COMMENT 'Human readable product name',
  CATEGORY     VARCHAR(50)  NOT NULL COMMENT 'Product category: Widgets, Gadgets or Accessories',
  UNIT_PRICE   NUMBER(10,2) NOT NULL COMMENT 'List price per unit in USD'
) COMMENT = 'Product dimension for the chart-rendering repro demo';

INSERT INTO CHART_SUBAGENT_DEMO.DEMO.PRODUCTS VALUES
  (1,'Alpha Widget','Widgets',25.00),
  (2,'Beta Widget','Widgets',32.50),
  (3,'Gamma Gadget','Gadgets',110.00),
  (4,'Delta Gadget','Gadgets',145.75),
  (5,'Epsilon Gadget','Gadgets',99.99),
  (6,'Zeta Accessory','Accessories',12.25),
  (7,'Eta Accessory','Accessories',18.40),
  (8,'Theta Widget','Widgets',41.00);

CREATE OR REPLACE TABLE CHART_SUBAGENT_DEMO.DEMO.SALES (
  ORDER_ID     NUMBER(12,0) NOT NULL COMMENT 'Unique identifier for the sales order line',
  ORDER_DATE   DATE         NOT NULL COMMENT 'Date the order was placed',
  PRODUCT_ID   NUMBER(9,0)  NOT NULL COMMENT 'Foreign key to PRODUCTS.PRODUCT_ID',
  REGION       VARCHAR(20)  NOT NULL COMMENT 'Sales region: North, South, East or West',
  QUANTITY     NUMBER(9,0)  NOT NULL COMMENT 'Units sold on this order line',
  NET_REVENUE  NUMBER(12,2) NOT NULL COMMENT 'Net revenue for this order line in USD'
) COMMENT = 'Sales fact table for the chart-rendering repro demo';

INSERT INTO CHART_SUBAGENT_DEMO.DEMO.SALES
SELECT
  SEQ4() + 1                                                                AS ORDER_ID,
  DATEADD(day, -1 * UNIFORM(0, 364, RANDOM(11)), DATE '2026-09-14')         AS ORDER_DATE,
  UNIFORM(1, 8, RANDOM(22))                                                 AS PRODUCT_ID,
  DECODE(UNIFORM(1, 4, RANDOM(33)), 1,'North', 2,'South', 3,'East', 'West') AS REGION,
  UNIFORM(1, 40, RANDOM(44))                                                AS QUANTITY,
  0                                                                         AS NET_REVENUE
FROM TABLE(GENERATOR(ROWCOUNT => 4000));

UPDATE CHART_SUBAGENT_DEMO.DEMO.SALES s
SET NET_REVENUE = ROUND(s.QUANTITY * p.UNIT_PRICE, 2)
FROM CHART_SUBAGENT_DEMO.DEMO.PRODUCTS p
WHERE s.PRODUCT_ID = p.PRODUCT_ID;

CREATE OR REPLACE TABLE CHART_SUBAGENT_DEMO.DEMO.INVENTORY (
  SNAPSHOT_DATE  DATE         NOT NULL COMMENT 'Date of the inventory snapshot',
  PRODUCT_ID     NUMBER(9,0)  NOT NULL COMMENT 'Foreign key to PRODUCTS.PRODUCT_ID',
  WAREHOUSE_CODE VARCHAR(20)  NOT NULL COMMENT 'Distribution center code holding the stock',
  UNITS_ON_HAND  NUMBER(9,0)  NOT NULL COMMENT 'Units physically available in the warehouse',
  UNITS_ON_ORDER NUMBER(9,0)  NOT NULL COMMENT 'Units already on a purchase order but not yet received',
  REORDER_POINT  NUMBER(9,0)  NOT NULL COMMENT 'Stock level at which replenishment should be triggered',
  STOCK_VALUE    NUMBER(14,2)          COMMENT 'Value of on-hand stock in USD at list price'
) COMMENT = 'Inventory snapshot fact table for the chart-rendering repro demo';

INSERT INTO CHART_SUBAGENT_DEMO.DEMO.INVENTORY
  (SNAPSHOT_DATE, PRODUCT_ID, WAREHOUSE_CODE, UNITS_ON_HAND, UNITS_ON_ORDER, REORDER_POINT, STOCK_VALUE)
SELECT
  DATE '2026-09-14',
  p.PRODUCT_ID,
  w.WAREHOUSE_CODE,
  UNIFORM(20, 900, RANDOM(55)),
  UNIFORM(0, 300, RANDOM(66)),
  UNIFORM(50, 250, RANDOM(77)),
  NULL
FROM CHART_SUBAGENT_DEMO.DEMO.PRODUCTS p
CROSS JOIN (
  SELECT 'DC-CHICAGO' AS WAREHOUSE_CODE UNION ALL
  SELECT 'DC-DALLAS'  UNION ALL
  SELECT 'DC-NEWARK'  UNION ALL
  SELECT 'DC-RENO'
) w;

UPDATE CHART_SUBAGENT_DEMO.DEMO.INVENTORY i
SET STOCK_VALUE = ROUND(i.UNITS_ON_HAND * p.UNIT_PRICE, 2)
FROM CHART_SUBAGENT_DEMO.DEMO.PRODUCTS p
WHERE i.PRODUCT_ID = p.PRODUCT_ID;


/* ---------------------------------------------------------------------------
   STEP 2 - Two semantic views (Sales + Inventory), as in the report
   --------------------------------------------------------------------------- */
CREATE OR REPLACE SEMANTIC VIEW CHART_SUBAGENT_DEMO.DEMO.SALES_SV
  TABLES (
    SALES AS CHART_SUBAGENT_DEMO.DEMO.SALES
      PRIMARY KEY (ORDER_ID) COMMENT = 'One row per sales order line',
    PRODUCTS AS CHART_SUBAGENT_DEMO.DEMO.PRODUCTS
      PRIMARY KEY (PRODUCT_ID) COMMENT = 'Product master'
  )
  RELATIONSHIPS (
    SALES_TO_PRODUCTS AS SALES (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
  )
  FACTS (
    SALES.UNITS AS QUANTITY COMMENT = 'Units sold on an order line',
    SALES.REVENUE_AMOUNT AS NET_REVENUE COMMENT = 'Net revenue of an order line in USD'
  )
  DIMENSIONS (
    SALES.ORDER_DATE AS ORDER_DATE
      WITH SYNONYMS = ('sale date','transaction date','date')
      COMMENT = 'Date the order was placed',
    SALES.ORDER_MONTH AS DATE_TRUNC('month', ORDER_DATE)
      WITH SYNONYMS = ('month','sales month')
      COMMENT = 'Calendar month of the order, truncated to the first day of the month',
    SALES.REGION AS REGION
      WITH SYNONYMS = ('sales region','territory','geo')
      COMMENT = 'Sales region: North, South, East or West',
    PRODUCTS.PRODUCT_NAME AS PRODUCT_NAME
      WITH SYNONYMS = ('product','item','sku name')
      COMMENT = 'Human readable product name',
    PRODUCTS.CATEGORY AS CATEGORY
      WITH SYNONYMS = ('product category','product family')
      COMMENT = 'Product category: Widgets, Gadgets or Accessories',
    PRODUCTS.LIST_PRICE AS UNIT_PRICE
      WITH SYNONYMS = ('unit price','price')
      COMMENT = 'List price per unit in USD'
  )
  METRICS (
    SALES.TOTAL_REVENUE AS SUM(SALES.REVENUE_AMOUNT)
      WITH SYNONYMS = ('revenue','sales','total sales','net revenue')
      COMMENT = 'Total net revenue in USD',
    SALES.TOTAL_UNITS AS SUM(SALES.UNITS)
      WITH SYNONYMS = ('units','units sold','volume','quantity')
      COMMENT = 'Total units sold',
    SALES.ORDER_COUNT AS COUNT(SALES.ORDER_ID)
      WITH SYNONYMS = ('orders','number of orders','order lines')
      COMMENT = 'Number of sales order lines',
    SALES.AVG_ORDER_REVENUE AS AVG(SALES.REVENUE_AMOUNT)
      WITH SYNONYMS = ('average order value','aov','average revenue per order')
      COMMENT = 'Average net revenue per order line in USD'
  )
  COMMENT = 'Sales analytics model: revenue, units and orders by product, category, region and month.';

CREATE OR REPLACE SEMANTIC VIEW CHART_SUBAGENT_DEMO.DEMO.INVENTORY_SV
  TABLES (
    INVENTORY AS CHART_SUBAGENT_DEMO.DEMO.INVENTORY
      PRIMARY KEY (SNAPSHOT_DATE, PRODUCT_ID, WAREHOUSE_CODE)
      COMMENT = 'One row per product per warehouse per snapshot date',
    PRODUCTS AS CHART_SUBAGENT_DEMO.DEMO.PRODUCTS
      PRIMARY KEY (PRODUCT_ID) COMMENT = 'Product master'
  )
  RELATIONSHIPS (
    INVENTORY_TO_PRODUCTS AS INVENTORY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
  )
  FACTS (
    INVENTORY.ON_HAND AS UNITS_ON_HAND COMMENT = 'Units physically on hand',
    INVENTORY.ON_ORDER AS UNITS_ON_ORDER COMMENT = 'Units on an open purchase order',
    INVENTORY.REORDER_LEVEL AS REORDER_POINT COMMENT = 'Reorder trigger level',
    INVENTORY.STOCK_VALUE_AMOUNT AS STOCK_VALUE COMMENT = 'Value of on-hand stock in USD at list price'
  )
  DIMENSIONS (
    INVENTORY.SNAPSHOT_DATE AS SNAPSHOT_DATE
      WITH SYNONYMS = ('as of date','inventory date')
      COMMENT = 'Date of the inventory snapshot',
    INVENTORY.WAREHOUSE_CODE AS WAREHOUSE_CODE
      WITH SYNONYMS = ('warehouse','dc','distribution center','location')
      COMMENT = 'Distribution center code holding the stock',
    PRODUCTS.PRODUCT_NAME AS PRODUCT_NAME
      WITH SYNONYMS = ('product','item','sku name')
      COMMENT = 'Human readable product name',
    PRODUCTS.CATEGORY AS CATEGORY
      WITH SYNONYMS = ('product category','product family')
      COMMENT = 'Product category: Widgets, Gadgets or Accessories'
  )
  METRICS (
    INVENTORY.TOTAL_ON_HAND AS SUM(INVENTORY.ON_HAND)
      WITH SYNONYMS = ('on hand','stock','units on hand','inventory level')
      COMMENT = 'Total units on hand',
    INVENTORY.TOTAL_ON_ORDER AS SUM(INVENTORY.ON_ORDER)
      WITH SYNONYMS = ('on order','incoming stock','open po units')
      COMMENT = 'Total units on open purchase orders',
    INVENTORY.TOTAL_STOCK_VALUE AS SUM(INVENTORY.STOCK_VALUE_AMOUNT)
      WITH SYNONYMS = ('stock value','inventory value')
      COMMENT = 'Total value of on-hand stock in USD',
    INVENTORY.AVG_REORDER_POINT AS AVG(INVENTORY.REORDER_LEVEL)
      WITH SYNONYMS = ('average reorder point')
      COMMENT = 'Average reorder trigger level'
  )
  COMMENT = 'Inventory analytics model: on-hand, on-order and stock value by product, category and warehouse.';


/* ---------------------------------------------------------------------------
   STEP 3 - SUBAGENT: owns both semantic views. Deliberately has NO chart tool.
   --------------------------------------------------------------------------- */
CREATE OR REPLACE AGENT SNOWFLAKE_INTELLIGENCE.AGENTS.DEMO_DATA_SUBAGENT
  COMMENT = 'Repro demo SUBAGENT: owns the Sales and Inventory semantic views and returns SQL result sets.'
  PROFILE = '{"display_name": "Demo Data Subagent (Sales + Inventory)", "color": "green"}'
  FROM SPECIFICATION
$$
models:
  orchestration: auto

orchestration:
  budget:
    seconds: 300
    tokens: 200000

instructions:
  response: |
    Return the full result set as a markdown table. Never truncate rows: if the query
    returns 5 rows, show all 5 rows. Do not summarise the data down to a sentence and
    do not editorialise - the caller needs the raw tabular data.
  orchestration: |
    You are a data retrieval subagent. You own two Cortex Analyst tools:
      - query_sales for anything about revenue, units sold, orders, products, categories, regions or sales months.
      - query_inventory for anything about units on hand, units on order, stock value, reorder points or warehouses.
    Always execute the generated SQL and return the actual rows.

tools:
  - tool_spec:
      type: cortex_analyst_text_to_sql
      name: query_sales
      description: |
        Queries the SALES_SV semantic view for sales performance.
        Metrics: total_revenue (USD), total_units, order_count, avg_order_revenue.
        Dimensions: product_name, category (Widgets/Gadgets/Accessories), region
        (North/South/East/West), order_date, order_month.
        Use for: revenue or unit rankings by product, category or region, and monthly trends.
        Do NOT use for stock levels or warehouse questions - use query_inventory instead.
  - tool_spec:
      type: cortex_analyst_text_to_sql
      name: query_inventory
      description: |
        Queries the INVENTORY_SV semantic view for the current inventory snapshot (2026-09-14).
        Metrics: total_on_hand, total_on_order, total_stock_value (USD), avg_reorder_point.
        Dimensions: product_name, category, warehouse_code (DC-CHICAGO/DC-DALLAS/DC-NEWARK/DC-RENO), snapshot_date.
        Use for: stock levels, stock value and replenishment questions by product, category or warehouse.
        Do NOT use for revenue or units sold - use query_sales instead.

tool_resources:
  query_sales:
    semantic_view: CHART_SUBAGENT_DEMO.DEMO.SALES_SV
    execution_environment:
      type: warehouse
      warehouse: COMPUTE_WH
      query_timeout: 120
  query_inventory:
    semantic_view: CHART_SUBAGENT_DEMO.DEMO.INVENTORY_SV
    execution_environment:
      type: warehouse
      warehouse: COMPUTE_WH
      query_timeout: 120
$$;


/* ---------------------------------------------------------------------------
   STEP 4 - MASTER AGENT: reaches the semantic views ONLY through the subagent,
            and owns data_to_chart.

   >>> THE CRITICAL BIT <<<
   The subagent is referenced with tool type `agent_toolset` and resource key
   `agent_name`. This is the only supported master->subagent mechanism.
   `type: agent` will be ACCEPTED by CREATE AGENT but FAILS at run time with
   "Tool type agent is not valid."
   --------------------------------------------------------------------------- */
CREATE OR REPLACE AGENT SNOWFLAKE_INTELLIGENCE.AGENTS.DEMO_MASTER_AGENT
  COMMENT = 'Repro demo MASTER agent: reaches the Sales/Inventory semantic views only through DEMO_DATA_SUBAGENT, and owns data_to_chart.'
  PROFILE = '{"display_name": "Demo Master Agent (charts via subagent)", "color": "blue"}'
  FROM SPECIFICATION
$$
models:
  orchestration: auto

orchestration:
  budget:
    seconds: 600
    tokens: 400000

instructions:
  response: |
    Present multi-row results as a table AND, when the result has more than 3 rows and
    contains at least one numeric measure, always render a chart with the data_to_chart tool.
    Always include units (USD, units).
  orchestration: |
    You are the master orchestrator. You do not own any semantic view directly.

    To obtain data, call the sales_inventory_data toolset, which reaches the Sales and
    Inventory analytics models. Pass the user's analytical question through in full.

    CHARTING RULE - this is mandatory:
    After you receive a result set, if it has MORE THAN 3 ROWS and includes at least one
    numeric column, you MUST call data_to_chart on that result set before writing your
    final answer. Choose the chart type that fits: bar for rankings and category
    comparisons, line for anything trended over time, pie only for share-of-total with
    fewer than 8 slices. Never describe a chart in text instead of calling data_to_chart.

tools:
  - tool_spec:
      type: agent_toolset
      name: sales_inventory_data
      description: |
        Retrieves sales and inventory result sets. Use for ANY question about revenue,
        units sold, orders, products, categories, regions, sales months, stock on hand,
        stock value, reorder points or warehouses. This is your only route to data.
  - tool_spec:
      type: data_to_chart
      name: data_to_chart
      description: |
        Renders a result set as an interactive chart. Call this whenever you have a
        result set with more than 3 rows and at least one numeric measure, including
        result sets that were retrieved through the sales_inventory_data toolset.

tool_resources:
  sales_inventory_data:
    agent_name: SNOWFLAKE_INTELLIGENCE.AGENTS.DEMO_DATA_SUBAGENT
$$;


/* ---------------------------------------------------------------------------
   STEP 5 - Verify
   --------------------------------------------------------------------------- */
DESCRIBE AGENT SNOWFLAKE_INTELLIGENCE.AGENTS.DEMO_MASTER_AGENT;

-- The exact question from the report. Returns 5 rows -> master agent calls
-- data_to_chart -> emits a response.chart event with a Vega-Lite v5 spec.
SELECT SNOWFLAKE.CORTEX.DATA_AGENT_RUN(
  'SNOWFLAKE_INTELLIGENCE.AGENTS.DEMO_MASTER_AGENT',
  '{"messages":[{"role":"user","content":[{"type":"text","text":"Show me sales by product for the top 5 products."}]}]}'
) AS MASTER_AGENT_RESPONSE;

/* Other questions verified to produce charts through the subagent:
     "Show me monthly total revenue trend for the last 12 months."          -> 12-row line chart
     "Show me total stock value by warehouse, and separately units on hand
      for all 8 products."                                                  -> 2 charts in one turn
*/

/* ---------------------------------------------------------------------------
   TEARDOWN
   ---------------------------------------------------------------------------
DROP AGENT IF EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS.DEMO_MASTER_AGENT;
DROP AGENT IF EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS.DEMO_DATA_SUBAGENT;
DROP DATABASE IF EXISTS CHART_SUBAGENT_DEMO;
*/
